#!/bin/bash

shopt -s nocasematch

query="{query}"
[ $query = "{query}" ] && query="$@"

devices=$(system_profiler SPBluetoothDataType -detailLevel mini -xml | 
  plutil -extract '0._items.0.device_title' xml1 -o - - |
  xpath '/plist/array/dict/dict/key[.="device_services"]/following-sibling::*[1]/text()')

echo '<?xml version="1.0"?>'
echo '<items>'
IFS=$'\n'
for device in $devices; do
  if [[ -n $query && ! $device =~ $query ]]; then
    continue
  fi
  cat <<_END_OF_ITEM_
  <item uid="$device" arg="$device">
    <title>$device</title>
    <subtitle>switch $device</subtitle>
  </item>
_END_OF_ITEM_
done
echo '</items>'
